#Config File for PvPLevels
---

#Floating Texts
#Set world to what world you want the texts to spawn in. Currently only supports one world.
texts:
  world: "world"
  #How frequently in seconds Floating Texts should update. Set to false to turn off timer.
  timer: 30

#Set title to whatever text you want to display at the top of the floating text for each statistic. Use "&" for colors.
  levels: "&b< PvP Levels Leaderboard >"
  kills: "&b< Kills Leaderboard >"
  kdr: "&b< K/D Ratio Leaderboard >"
  streaks: "&b< Top Killstreaks >"
#Top X rankings. If you put 5, only the top 5 will be shown. 10 will result in top 10, etc.
  top: 5

#Format:
# Level Number:
#   kills: number of kills required
#   commands: commands to be run upon leveling up
# Variables you can use:
# %k = # of kills
# %s = Kill streak
# %d = # of deaths
# %p = Player name
# %l = PvP Level
# %kdr = Kills/Deaths ratio of player

#Keep the config formatted correctly or you may get errors.
# Make sure you don't skip levels.


0:
  kills: 0
  #Leave this one blank
1:
  kills: 5
  commands: 
  - "say %p is now level 1"
  - "give %p cookie 1"
2: 
  kills: 10
  commands:
  - "say %p got 10 kills"